Socializer/config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
    root to: 'posts#index', as: :authenticated_root
  end
  

  root to: redirect('/users/sign_in')
  
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  
  resources :posts do
    resources :comments
  end
  

end

Socializer/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

Socializer/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  
  validates :user_id, presence: true
  validates :image, presence: true
  validates :caption, length: { minimum: 2, maximum: 300 }
  
  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

Socializer/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  
  has_attached_file :avatar, styles: { medium: '152x152#' }  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

Socializer/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  
  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    
    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = "Error. Please check the form and resubmit."
      render root_path
    end
  end
  
  def destroy
    @comment = @post.comments.find(params[:id])
    
    if @comment.user_id == current_user.id
      @comment.delete
      flash[:success] = "Comment deleted."
      redirect_to root_path
    end
  end
  
  private
    def comment_params
      params.require(:comment).permit(:content)
    end
    
    def set_post
      @post = Post.find(params[:post_id])
    end
end

Socializer/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :post_protect, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    
    if @post.save
      redirect_to profile_path(current_user.user_name)
    else
      flash.now[:alert] = "Image or caption field can't be blank"
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Updated successfully"
      redirect_to profile_path(current_user.user_name)
    else
      flash.now[:alert] = "Error! Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted."
    redirect_to profile_path(current_user.user_name)
  end

  private

    def post_params
      params.require(:post).permit(:image, :caption)
    end
    
    def set_post
      @post = Post.find(params[:id]) # Removing repeated code with this method
    end
    
    def post_protect
      unless current_user == @post.user
        flash[:alert] = "Unauthorized"
        redirect_to root_path
      end
    end
end  

Socializer/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :owned_profile, only: [:edit, :update]
  
  def show
    @user = User.find_by(user_name: params[:user_name])
    @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end
  
  def edit  
    @user = User.find_by(user_name: params[:user_name])
  end 
  
  def update  
    @user = User.find_by(user_name: params[:user_name])
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end
  
  private

    def profile_params  
      params.require(:user).permit(:avatar, :bio)
    end
    
    def owned_profile  
      @user = User.find_by(user_name: params[:user_name])
      unless current_user == @user
        flash[:alert] = "You don't have permission to access this page."
        redirect_to root_path
      end
    end
end

Socializer/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

Socializer/app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)  
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
  
  def form_image_select(post)  
    return image_tag post.image.url(:medium),
                     id: 'image-preview',
                     class: 'img-responsive' if post.image.exists?
    image_tag 'placeholder.jpg', id: 'image-preview', class: 'img-responsive'
  end
  
  def profile_avatar_select(user)  
    return image_tag user.avatar.url(:medium),
                     id: 'image-preview',
                     class: 'img-responsive img-circle profile-image' if user.avatar.exists?
    image_tag 'default-avatar.png', id: 'image-preview',
                                    class: 'img-responsive img-circle profile-image'
  end
end

Socializer/app/helpers/comments_helper.rb
module CommentsHelper
end

Socializer/app/helpers/posts_helper.rb
module PostsHelper
end

Socializer/app/helpers/profiles_helper.rb
module ProfilesHelper
end

Socializer/app/views/comments/_comment.html.haml
#comment
  .user-name
    = link_to comment.user.user_name, profile_path(comment.user.user_name)
  .comment-content
    = comment.content
  -if comment.user == current_user
    = link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } do
      %span(class="glyphicon glyphicon-remove delete-comment")

Socializer/app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

Socializer/app/views/posts/_form.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_image_select(@post)
        = simple_form_for @post, html: { multipart: true } do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              %h4 Upload an image:
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
            .form-group.text-center
              = f.input :caption, label: false, placeholder: 'Add your caption', input_html: { class: 'input-lg test' }
            .form-group.text-center
              = f.button :submit, class: 'btn-lg btn-success btn-block'

Socializer/app/views/posts/_post.html.haml
.posts-wrapper.row
  .post
    .post-head
      .thumb-img
      .user-name
        = link_to post.user.user_name, profile_path(post.user.user_name)
      .time-ago
        = "#{time_ago_in_words(post.created_at)} ago "
    .image.center-block
      = link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post)
    .post-bottom
      .caption.text-center
        = post.caption
      .comments{id: "comments_#{post.id}"}
        - if post.comments
          = render post.comments, post: post
      .comment-form
        = form_for([post, post.comments.build], remote: true) do |f|
          = f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}"
          = f.button :submit, class: 'comment-submit'

Socializer/app/views/posts/edit.html.haml
=render 'form'
      
  

Socializer/app/views/posts/index.html.haml
-@posts.reverse.each do |post|
  = render 'post', post: post
        
              
          

Socializer/app/views/posts/new.html.haml
=render 'form'

Socializer/app/views/posts/show.html.haml
=render 'post', post: @post 

-if @post.user.id == current_user.id
  .text-center.edit-links
    =link_to "Return", posts_path 
    |
    =link_to "Edit", edit_post_path
    |
    =link_to "Delete Post", post_path(@post), method: :delete,
    data: { confirm: "Are you sure you want to delete this post?" }
-else
  .text-center.edit-links
    =link_to "Return", posts_path